[package]
name = "codecrafters-shell"
version = "0.1.0"
authors = ["Codecrafters <hello@codecrafters.io>"]
edition = "2021"
rust-version = "1.81"

[[bin]]
name = "codecrafters-shell"
path = "src/main.rs"

[dependencies]
termion = "4.0.4"
